### PR TITLE
Feature/target/home map

### PR DESCRIPTION
**Pull request by DanielPresa**
## Links (Jira/Trello ticket and other relevant links):
https://trello.com/c/BhjNV3pq/3-3-as-a-user-i-should-be-able-to-see-a-map-so-i-can-easily-identify-targets-in-the-future

## What & Why:
Added leaflet and added a map along with a wrapper to be placed in the home page.

## Screenshots:
Screen Shot 2021-08-16 at 14 05 14

### CODE REVIEW

**Comment by diebarral** [comment]
Please rebase this branch against `master` so we only see what this branch changes

**Comment by DanielPresa** [comment]
> Please rebase this branch against `master` so we only see what this branch changes

Done!

**Comment by diebarral** [comment]
> > Please rebase this branch against `master` so we only see what this branch changes
> 
> Done!

I see there are still issues addressed in the previous pull request. Maybe open a new branch from master and cherry-pick the last commit that contains the real changes from this branch (49d6b60806fca90af857bacdbf864b7e3da7a17e), and then create a new pull request.

**Comment by DanielPresa** [comment]
> > > Please rebase this branch against `master` so we only see what this branch changes
> > 
> > 
> > Done!
> 
> I see there are still issues addressed in the previous pull request. Maybe open a new branch from master and cherry-pick the last commit that contains the real changes from this branch ([49d6b60](https://github.com/DanielPresa/Target_React/commit/49d6b60806fca90af857bacdbf864b7e3da7a17e)), and then create a new pull request.

Then I'll be closing this one so as to make the new one and prevent any kind of disorder.

**Pull request closed without merging**
